name: Docker build

# Controls when the workflow will run
on:
  release:
    types:
      - published
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        base:
          - terraform:v4.0.1
          - cli-tools-core:v2.0.2
          - cli-tools-ibmcloud:v0.8.3
          - cli-tools:v3.0.2
        version:
          - v1.6
          - v1.7
          - v1.8
          - v1.9

    env:
      TERRAFORM_LATEST: "v1.9"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to CNTK Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_CNTK_USERNAME }}
          password: ${{ secrets.QUAY_CNTK_TOKEN }}

      - name: Setup variables ${{ matrix.base }}:${{ matrix.version }}
        id: variables
        shell: bash
        run: |
          SHORT_TERRAFORM=${{ matrix.version }}
          BASE=$(echo "${{ matrix.base }}" | sed -E "s/(.*):(.*)/\1/g") 
          BASE_VERSION=$(echo "${{ matrix.base }}" | sed -E "s/(.*):(.*)/\2/g") 
          
          SHORT_TAG_ENABLED="false"
          if [[ "${BASE}" == "cli-tools" ]]; then
            SHORT_TAG_ENABLED="true"
          fi
          
          BASE_ENABLED="false"
          LATEST_ENABLED="false"
          if [[ "${SHORT_TERRAFORM}" == "${TERRAFORM_LATEST}" ]]; then
            BASE_ENABLED="true"
            
            if [[ "${BASE}" == "cli-tools" ]]; then
              LATEST_ENABLED="true"
            fi
          fi
          
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_TAG_ENABLED="false"
          RELEASE_TAG_SHORT_ENABLED="false"
          if [[ "${GITHUB_REF}" =~ refs/tags ]] && [[ "${RELEASE_TAG}" != "main" ]]; then
            RELEASE_TAG_ENABLED="true"
          
            if [[ "${BASE}" == "cli-tools" ]]; then
              RELEASE_TAG_SHORT_ENABLED="true"
            fi
          else
            RELEASE_TAG="main"
          fi
          
          echo "Short terraform: ${SHORT_TERRAFORM}"
          echo "terraform=$SHORT_TERRAFORM" >> $GITHUB_OUTPUT
          
          echo "Short tag enabled: $SHORT_TAG_ENABLED"
          echo "short-enabled=$SHORT_TAG_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Release tag: ${RELEASE_TAG}"
          echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          
          echo "Release tag enabled: $RELEASE_TAG_ENABLED"
          echo "release-tag-enabled=$RELEASE_TAG_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Release tag short enabled: $RELEASE_TAG_SHORT_ENABLED"
          echo "release-tag-short-enabled=$RELEASE_TAG_SHORT_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Base enabled: $BASE_ENABLED"
          echo "base-enabled=$BASE_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Latest enabled: $LATEST_ENABLED"
          echo "latest-enabled=$LATEST_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Base: $BASE"
          echo "base=$BASE" >> $GITHUB_OUTPUT
          
          echo "Base version: $BASE_VERSION"
          echo "base-version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Docker CNTK meta ${{ matrix.base }}:${{ matrix.version }}
        id: cntk-meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/cloudnativetoolkit/github-terraform-runner
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.variables.outputs.terraform }}-${{ steps.variables.outputs.base }}
            type=raw,value=${{ steps.variables.outputs.terraform }},enable=${{ steps.variables.outputs.short-enabled }}
            type=raw,value=${{ steps.variables.outputs.terraform }}-${{ steps.variables.outputs.release-tag }}-${{ steps.variables.outputs.base }},enable=${{ steps.variables.outputs.release-tag-enabled }}
            type=raw,value=${{ steps.variables.outputs.terraform }}-${{ steps.variables.outputs.release-tag }},enable=${{ steps.variables.outputs.release-tag-short-enabled }}
            type=raw,value=${{ steps.variables.outputs.base }},enable=${{ steps.variables.outputs.base-enabled }}
            type=raw,value=latest,enable=${{ steps.variables.outputs.latest-enabled }}

      - name: Build and push ${{ matrix.base }}:${{ matrix.version }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Containerfile
          build-args: |
            IMAGE=quay.io/cloudnativetoolkit/${{ steps.variables.outputs.base }}:${{ matrix.version }}-${{ steps.variables.outputs.base-version }}-fedora
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.cntk-meta.outputs.tags }}
          labels: ${{ steps.cntk-meta.outputs.labels }}

  verify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Verify
        run: |
          echo "Success"
